export type BreastfeedingTip = {
  day: number;
  category: string;
  title: string;
  message: string;
  whyItMatters: string;
  motherTip: string;
  source: string;
};

export const breastfeedingTips: BreastfeedingTip[] = [
  {
    day: 1,
    category: "Early days",
    title: "Start early",
    message: "Starting breastfeeding within the first hour after birth helps a newborn begin receiving colostrum.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO/UNICEF",
  },
  {
    day: 2,
    category: "Early days",
    title: "Colostrum",
    message: "Colostrum is the first milk and is rich in protective components suited to newborns.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 3,
    category: "Early days",
    title: "Skin-to-skin",
    message: "Skin-to-skin contact can support early breastfeeding and helps keep a newborn warm.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO/UNICEF",
  },
  {
    day: 4,
    category: "Early days",
    title: "First feeds",
    message: "Newborns may feed frequently while mother and baby learn breastfeeding together.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 5,
    category: "Early days",
    title: "Responsive feeding",
    message: "Offer the breast when your baby shows feeding cues rather than waiting for intense crying.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 6,
    category: "Early days",
    title: "Night feeds",
    message: "Newborn feeding can happen day and night. Night feeds are normal in early infancy.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 7,
    category: "Early days",
    title: "Feeding cues",
    message: "Rooting, hand-to-mouth movements and stirring can be early signs that a baby is ready to feed.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 8,
    category: "Early days",
    title: "Crying",
    message: "Crying is often a later feeding cue. Responding earlier may make feeding easier.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 9,
    category: "Early days",
    title: "Attachment",
    message: "A comfortable, deep latch can support effective milk transfer and reduce nipple discomfort.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 10,
    category: "Milk and nutrition",
    title: "Water",
    message: "During exclusive breastfeeding, breast milk provides the water a healthy term infant needs.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 11,
    category: "Milk and nutrition",
    title: "Lactose",
    message: "Lactose is the main carbohydrate in human milk and supplies energy for growth.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 12,
    category: "Milk and nutrition",
    title: "Protein",
    message: "Human milk contains proteins that provide nutrition and also have protective functions.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 13,
    category: "Milk and nutrition",
    title: "Fats",
    message: "Milk fats provide concentrated energy and fatty acids important to infant development.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 14,
    category: "Milk and nutrition",
    title: "Vitamins",
    message: "Human milk supplies many vitamins and minerals, although some infants need specific supplements.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 15,
    category: "Milk and nutrition",
    title: "Enzymes",
    message: "Human milk contains enzymes that contribute to digestion and other biological functions.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 16,
    category: "Milk and nutrition",
    title: "Bioactive factors",
    message: "Human milk contains bioactive factors in addition to ordinary nutrients.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 17,
    category: "Milk and nutrition",
    title: "Changing milk",
    message: "Milk composition changes during lactation as the infant grows.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 18,
    category: "Milk and nutrition",
    title: "Mature milk",
    message: "Mature milk continues to provide nutrients and bioactive components throughout breastfeeding.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 19,
    category: "Immunity",
    title: "Antibodies",
    message: "Human milk contains antibodies, including secretory IgA, that help protect mucosal surfaces.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 20,
    category: "Immunity",
    title: "Lactoferrin",
    message: "Lactoferrin binds iron and contributes to the protective activity of human milk.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 21,
    category: "Immunity",
    title: "Lysozyme",
    message: "Lysozyme is an antimicrobial enzyme found in human milk.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 22,
    category: "Immunity",
    title: "Gut defense",
    message: "Several milk components help create a protective environment in the developing intestine.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 23,
    category: "Immunity",
    title: "Diarrhoea",
    message: "Breastfeeding helps protect infants against diarrhoeal illness.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 24,
    category: "Immunity",
    title: "Pneumonia",
    message: "Breastfeeding is associated with protection against common childhood illnesses such as pneumonia.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 25,
    category: "Immunity",
    title: "Illness",
    message: "During many childhood illnesses, continued breastfeeding helps maintain fluid and nutrient intake.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 26,
    category: "Immunity",
    title: "Microbes",
    message: "Human milk contains components that can help limit harmful microbial growth.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 27,
    category: "Immunity",
    title: "Protection",
    message: "Breast milk's immune components work alongside the baby's developing immune system.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 28,
    category: "Brain",
    title: "Brain nutrition",
    message: "Human milk provides nutrients and bioactive components that support infant growth and development.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 29,
    category: "Brain",
    title: "Fatty acids",
    message: "Long-chain fatty acids in human milk contribute to the nutritional environment supporting nervous-system development.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 30,
    category: "Brain",
    title: "Early development",
    message: "Good nutrition in infancy supports healthy brain and body development.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 31,
    category: "Brain",
    title: "Interaction",
    message: "Feeding provides opportunities for close interaction between baby and caregiver.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 32,
    category: "Brain",
    title: "Eye contact",
    message: "Gentle eye contact during feeding supports early parent-infant communication.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 33,
    category: "Brain",
    title: "Voice",
    message: "Talking and singing during feeding can support early communication and bonding.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 34,
    category: "Brain",
    title: "Responsive care",
    message: "Responding consistently to a baby's cues supports healthy early development.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 35,
    category: "Brain",
    title: "Learning",
    message: "Adequate infant nutrition provides a foundation for healthy growth and development.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 36,
    category: "Brain",
    title: "Growth",
    message: "Breastfeeding supports optimal growth and development during early infancy.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 37,
    category: "Eyes and senses",
    title: "Visual nutrition",
    message: "Fatty acids in human milk are part of the nutritional environment supporting visual and nervous-system development.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 38,
    category: "Eyes and senses",
    title: "Vision",
    message: "Normal visual development depends on adequate overall nutrition and healthy growth.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO/NCBI",
  },
  {
    day: 39,
    category: "Eyes and senses",
    title: "Senses",
    message: "Close feeding interactions give babies opportunities to see, hear and respond to their caregiver.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 40,
    category: "Eyes and senses",
    title: "Eye contact",
    message: "Looking at your baby during feeds can strengthen responsive interaction.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 41,
    category: "Eyes and senses",
    title: "Voice",
    message: "A calm voice during feeding provides familiar sound and social interaction.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 42,
    category: "Eyes and senses",
    title: "Touch",
    message: "Gentle touch during feeding supports closeness and responsive care.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 43,
    category: "Eyes and senses",
    title: "Attention",
    message: "Following your baby's cues helps build responsive feeding habits.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 44,
    category: "Eyes and senses",
    title: "Development",
    message: "Breastfeeding is one part of a broader environment supporting healthy infant development.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 45,
    category: "Eyes and senses",
    title: "Check concerns",
    message: "If you notice concerns about your baby's vision or development, seek professional assessment.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 46,
    category: "Gut and digestion",
    title: "Easy digestion",
    message: "Breast milk is generally easy for infants to digest.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF Nigeria",
  },
  {
    day: 47,
    category: "Gut and digestion",
    title: "Gut microbiome",
    message: "Breastfeeding helps shape the developing infant gut microbiome.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 48,
    category: "Gut and digestion",
    title: "Oligosaccharides",
    message: "Human milk oligosaccharides support beneficial gut bacteria and help protect the intestine.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 49,
    category: "Gut and digestion",
    title: "Prebiotic action",
    message: "Milk oligosaccharides act as substrates for beneficial microbes in the infant gut.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 50,
    category: "Gut and digestion",
    title: "Gut barrier",
    message: "Milk bioactive factors contribute to the developing intestinal environment.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 51,
    category: "Gut and digestion",
    title: "Stool changes",
    message: "A breastfed baby's stool pattern can change during the early months.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 52,
    category: "Gut and digestion",
    title: "Hydration",
    message: "For healthy term infants under six months, breast milk provides fluid without routine extra water.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 53,
    category: "Gut and digestion",
    title: "No routine water",
    message: "Exclusive breastfeeding means no additional water or other drinks for healthy infants under six months.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 54,
    category: "Gut and digestion",
    title: "Seek help",
    message: "Persistent vomiting, poor feeding or concerning stool changes should be discussed with a health worker.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 55,
    category: "Growth and body",
    title: "Healthy growth",
    message: "Breastfeeding supports healthy growth and development in infancy.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 56,
    category: "Growth and body",
    title: "Healthy weight",
    message: "Breastfeeding is associated with a lower risk of overweight and obesity later in childhood.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 57,
    category: "Growth and body",
    title: "Bones",
    message: "Human milk provides nutrients and minerals that contribute to normal infant growth.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO/NCBI",
  },
  {
    day: 58,
    category: "Growth and body",
    title: "Muscles",
    message: "Adequate nutrition supports normal muscle growth and physical development.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 59,
    category: "Growth and body",
    title: "Skin",
    message: "Adequate feeding and hydration support normal skin and body function.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 60,
    category: "Growth and body",
    title: "Blood",
    message: "Iron status deserves attention because human milk is not a high-iron food; discuss needs with a clinician.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 61,
    category: "Growth and body",
    title: "Growth checks",
    message: "Routine growth monitoring helps confirm that a baby is growing appropriately.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 62,
    category: "Growth and body",
    title: "Wet nappies",
    message: "Wet nappies are one useful sign when assessing whether a baby is receiving enough milk.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 63,
    category: "Growth and body",
    title: "Development",
    message: "Growth includes physical, cognitive and social development, not weight alone.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 64,
    category: "Mother",
    title: "Mother's health",
    message: "Breastfeeding provides important health benefits for mothers as well as infants.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 65,
    category: "Mother",
    title: "Recovery",
    message: "Breastfeeding triggers hormonal responses that support the postpartum period.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 66,
    category: "Mother",
    title: "Rest",
    message: "Accept practical help so you can rest whenever opportunities arise.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 67,
    category: "Mother",
    title: "Nutrition",
    message: "A varied, balanced diet supports the mother's health while breastfeeding.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 68,
    category: "Mother",
    title: "Drink to thirst",
    message: "Drink according to thirst rather than forcing excessive amounts of fluid to increase milk supply.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 69,
    category: "Mother",
    title: "Support",
    message: "Practical and emotional support can make breastfeeding easier to sustain.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 70,
    category: "Mother",
    title: "Mental wellbeing",
    message: "Persistent sadness or anxiety deserves professional support. Asking for help is not failure.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 71,
    category: "Mother",
    title: "Postpartum depression",
    message: "Postpartum depression is a real health condition and deserves assessment and treatment.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 72,
    category: "Mother",
    title: "Respect",
    message: "Mothers deserve respectful, non-judgmental breastfeeding support.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO/UNICEF",
  },
  {
    day: 73,
    category: "Feeding challenges",
    title: "Pain",
    message: "Persistent nipple pain should be assessed rather than simply endured.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 74,
    category: "Feeding challenges",
    title: "Low supply concern",
    message: "Breast fullness alone does not reliably measure milk supply; growth and feeding effectiveness matter more.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 75,
    category: "Feeding challenges",
    title: "Frequent feeding",
    message: "Periods of frequent feeding can occur during normal infant development.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 76,
    category: "Feeding challenges",
    title: "Cluster feeding",
    message: "Cluster feeding can be normal and does not automatically mean that milk supply is low.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 77,
    category: "Feeding challenges",
    title: "Engorgement",
    message: "Frequent effective milk removal can help relieve breast fullness and engorgement.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 78,
    category: "Feeding challenges",
    title: "Mastitis",
    message: "Breast redness, swelling, pain or fever should be discussed promptly with a health professional.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 79,
    category: "Feeding challenges",
    title: "Nipple injury",
    message: "Cracked or bleeding nipples deserve assessment for attachment and other causes.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 80,
    category: "Feeding challenges",
    title: "Latch help",
    message: "A trained breastfeeding counsellor can observe a feed and help with attachment.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 81,
    category: "Feeding challenges",
    title: "Early help",
    message: "Seeking skilled help early can prevent small feeding problems from becoming bigger ones.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 82,
    category: "Safety",
    title: "No honey",
    message: "Honey is not appropriate for infants under one year because of the risk of infant botulism.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "CDC",
  },
  {
    day: 83,
    category: "Safety",
    title: "No herbal mixtures",
    message: "Do not give newborns herbal mixtures or other liquids without qualified medical advice.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 84,
    category: "Safety",
    title: "No early solids",
    message: "Healthy term infants should generally receive only breast milk for the first six months.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 85,
    category: "Safety",
    title: "No routine gripe water",
    message: "Routine water-based products are inconsistent with exclusive breastfeeding recommendations.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 86,
    category: "Safety",
    title: "Smoking",
    message: "Avoid tobacco smoke around babies because second-hand smoke harms child health.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 87,
    category: "Safety",
    title: "Alcohol",
    message: "Ask a trusted health professional about alcohol and breastfeeding rather than relying on myths.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "CDC",
  },
  {
    day: 88,
    category: "Safety",
    title: "Medicines",
    message: "Ask a healthcare professional before stopping breastfeeding because of a medicine.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 89,
    category: "Safety",
    title: "Herbal medicines",
    message: "Natural does not automatically mean safe during breastfeeding. Discuss herbal products with a professional.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 90,
    category: "Safety",
    title: "Safe sleep",
    message: "Breastfeeding does not replace safe-sleep practices. Follow trusted safe-sleep guidance.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 91,
    category: "Expressing and storage",
    title: "Expressing",
    message: "Expressing milk can help when direct breastfeeding is temporarily difficult or mother and baby are separated.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 92,
    category: "Expressing and storage",
    title: "Clean hands",
    message: "Wash hands appropriately before expressing or handling breast milk.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO/CDC",
  },
  {
    day: 93,
    category: "Expressing and storage",
    title: "Clean containers",
    message: "Use clean, food-safe containers for expressed milk.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO/CDC",
  },
  {
    day: 94,
    category: "Expressing and storage",
    title: "Storage",
    message: "Follow current health-authority guidance for safe breast-milk storage.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO/CDC",
  },
  {
    day: 95,
    category: "Expressing and storage",
    title: "Labelling",
    message: "When storing expressed milk, clear labelling can help track when it was expressed.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "CDC",
  },
  {
    day: 96,
    category: "Expressing and storage",
    title: "Transport",
    message: "Keep expressed milk protected from contamination and follow recommended temperature guidance.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "CDC",
  },
  {
    day: 97,
    category: "Expressing and storage",
    title: "Pump care",
    message: "Clean breast-pump parts according to the manufacturer's instructions.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "CDC",
  },
  {
    day: 98,
    category: "Expressing and storage",
    title: "Work planning",
    message: "Mothers returning to work can plan feeding and milk-expression arrangements ahead of time.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 99,
    category: "Expressing and storage",
    title: "Support at work",
    message: "Workplace support can help mothers continue breastfeeding or expressing milk.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO/UNICEF",
  },
  {
    day: 100,
    category: "Family and community",
    title: "Partner",
    message: "A partner can protect feeding time and help with household tasks.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 101,
    category: "Family and community",
    title: "Grandparents",
    message: "Family members can encourage evidence-based breastfeeding practices instead of harmful myths.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 102,
    category: "Family and community",
    title: "Community",
    message: "Community support can help mothers overcome common breastfeeding challenges.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 103,
    category: "Family and community",
    title: "Health worker",
    message: "Keep contact with a qualified health worker for feeding questions.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 104,
    category: "Family and community",
    title: "Counselling",
    message: "Breastfeeding counselling can help mothers build skills and confidence.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 105,
    category: "Family and community",
    title: "No shame",
    message: "Mothers need accurate information and support, not shame or pressure.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 106,
    category: "Family and community",
    title: "Public feeding",
    message: "Mothers should be supported to feed their babies wherever feeding is needed.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO/UNICEF",
  },
  {
    day: 107,
    category: "Family and community",
    title: "Respect choices",
    message: "Feeding situations differ. Support should remain respectful and informed.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 108,
    category: "Family and community",
    title: "Shared care",
    message: "Family support can free mothers to focus on feeding and recovery.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 109,
    category: "Common illnesses",
    title: "Diarrhoea",
    message: "Continue breastfeeding during diarrhoea while seeking appropriate medical care.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 110,
    category: "Common illnesses",
    title: "ORS",
    message: "Oral rehydration solution may be medically indicated for diarrhoea; it does not replace breastfeeding.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 111,
    category: "Common illnesses",
    title: "Fever",
    message: "A young infant with fever needs prompt medical assessment.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 112,
    category: "Common illnesses",
    title: "Breathing",
    message: "Difficulty breathing in a young infant requires urgent medical attention.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 113,
    category: "Common illnesses",
    title: "Poor feeding",
    message: "A sudden change to poor feeding should be taken seriously.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 114,
    category: "Common illnesses",
    title: "Sleepiness",
    message: "A baby who is unusually difficult to wake for feeds should be assessed promptly.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 115,
    category: "Common illnesses",
    title: "Jaundice",
    message: "Increasing jaundice or difficulty waking for feeds should be discussed promptly with a health professional.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 116,
    category: "Common illnesses",
    title: "Dehydration",
    message: "Reduced urination or unusual sleepiness can be warning signs requiring medical attention.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 117,
    category: "Common illnesses",
    title: "Vaccination",
    message: "Breastfeeding supports health but does not replace routine childhood vaccination.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 118,
    category: "Special situations",
    title: "Prematurity",
    message: "Premature babies may need individualized feeding support and expressed milk.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 119,
    category: "Special situations",
    title: "Twins",
    message: "Mothers of twins can breastfeed and may benefit from individualized support.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 120,
    category: "Special situations",
    title: "Cesarean",
    message: "A cesarean birth does not automatically prevent breastfeeding.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 121,
    category: "Special situations",
    title: "Maternal illness",
    message: "Many maternal illnesses do not automatically require breastfeeding to stop; seek specific medical advice.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 122,
    category: "Special situations",
    title: "HIV",
    message: "Where HIV is present, feeding recommendations depend on current national and clinical guidance.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 123,
    category: "Special situations",
    title: "Tuberculosis",
    message: "Some infections require specific precautions rather than automatically stopping breastfeeding.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 124,
    category: "Special situations",
    title: "Medication",
    message: "Medication decisions should be made with a qualified clinician.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 125,
    category: "Special situations",
    title: "Medical needs",
    message: "Babies with medical conditions may require individualized feeding plans.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 126,
    category: "Special situations",
    title: "Premature support",
    message: "Specialist neonatal feeding support can help protect nutrition for premature infants.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 127,
    category: "Month 1",
    title: "Week one",
    message: "The first week is a learning period. Frequent feeds and support are normal.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 128,
    category: "Month 1",
    title: "Week two",
    message: "Continue watching feeding cues and monitoring your baby's growth.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 129,
    category: "Month 1",
    title: "Week three",
    message: "If feeding remains painful or difficult, seek skilled breastfeeding support.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 130,
    category: "Month 1",
    title: "Week four",
    message: "Routine infant health checks are an opportunity to discuss feeding concerns.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 131,
    category: "Month 1",
    title: "One month",
    message: "A baby's feeding pattern may still change frequently during the first month.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 132,
    category: "Month 1",
    title: "Supply",
    message: "Frequent effective milk removal helps maintain milk production.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 133,
    category: "Month 1",
    title: "Attachment",
    message: "A comfortable latch supports milk transfer and can reduce pain.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 134,
    category: "Month 1",
    title: "Growth",
    message: "Healthy growth is more useful than guessing milk supply from breast fullness.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 135,
    category: "Month 1",
    title: "Support",
    message: "Accept help with meals, chores and rest during the demanding first month.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 136,
    category: "Months 2–3",
    title: "Two months",
    message: "Continue responsive breastfeeding day and night.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 137,
    category: "Months 2–3",
    title: "Growth",
    message: "Infants grow at different rates; use health-worker growth monitoring rather than comparison.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 138,
    category: "Months 2–3",
    title: "Cues",
    message: "Keep responding to rooting, hand-to-mouth movements and other feeding cues.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 139,
    category: "Months 2–3",
    title: "Interaction",
    message: "Talk, look and respond to your baby during feeds.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 140,
    category: "Months 2–3",
    title: "Immunization",
    message: "Keep routine immunization appointments while continuing breastfeeding.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 141,
    category: "Months 2–3",
    title: "Three months",
    message: "Feeding patterns may change as babies become more alert and active.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 142,
    category: "Months 2–3",
    title: "No water",
    message: "Do not routinely add water during exclusive breastfeeding before six months.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 143,
    category: "Months 2–3",
    title: "No solids",
    message: "Complementary foods are generally introduced around six months, not at three months.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 144,
    category: "Months 2–3",
    title: "Support",
    message: "Ask for help if feeding suddenly becomes difficult or your baby's growth concerns you.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 145,
    category: "Months 4–5",
    title: "Four months",
    message: "Continue exclusive breastfeeding for a healthy term infant unless individualized medical advice says otherwise.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 146,
    category: "Months 4–5",
    title: "Feeding cues",
    message: "Continue responding to your baby's hunger and fullness cues.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 147,
    category: "Months 4–5",
    title: "Development",
    message: "Babies become more alert and interactive, but breast milk remains their primary food.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 148,
    category: "Months 4–5",
    title: "No early solids",
    message: "Starting solids too early is not the WHO recommendation for healthy term infants.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 149,
    category: "Months 4–5",
    title: "No water",
    message: "Breast milk continues to provide food and water during exclusive breastfeeding.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 150,
    category: "Months 4–5",
    title: "Prepare",
    message: "Use the fifth month to learn about safe complementary feeding.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 151,
    category: "Months 4–5",
    title: "Five months",
    message: "Discuss the upcoming transition to complementary foods with a health worker.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 152,
    category: "Months 4–5",
    title: "Continue",
    message: "Breastfeeding does not need to stop when complementary foods begin.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 153,
    category: "Months 4–5",
    title: "Support",
    message: "Plan family support for the transition around six months.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 154,
    category: "Six months transition",
    title: "Six-month milestone",
    message: "At around six months, babies need complementary foods while breastfeeding continues.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 155,
    category: "Six months transition",
    title: "Complementary",
    message: "Complementary foods are added alongside breast milk, not instead of it immediately.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 156,
    category: "Six months transition",
    title: "Food safety",
    message: "Prepare complementary foods safely and hygienically.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 157,
    category: "Six months transition",
    title: "Food diversity",
    message: "Offer a variety of nutritious foods as complementary feeding develops.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 158,
    category: "Six months transition",
    title: "Iron-rich foods",
    message: "Nutrient-dense and iron-rich foods are important as complementary feeding begins.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 159,
    category: "Six months transition",
    title: "Responsive feeding",
    message: "Continue responding to hunger and fullness cues when introducing foods.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 160,
    category: "Six months transition",
    title: "Continue breastfeeding",
    message: "WHO recommends continued breastfeeding with complementary foods up to two years or beyond.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 161,
    category: "Six months transition",
    title: "Texture",
    message: "Introduce age-appropriate textures gradually as the child develops feeding skills.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 162,
    category: "Six months transition",
    title: "Family support",
    message: "Family members can help with safe food preparation while protecting breastfeeding time.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "UNICEF",
  },
  {
    day: 163,
    category: "Breast-milk components",
    title: "Oligosaccharides",
    message: "Human milk oligosaccharides help shape the infant gut microbiome and support intestinal protection.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 164,
    category: "Breast-milk components",
    title: "Secretory IgA",
    message: "Secretory IgA contributes to immune protection at mucosal surfaces.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 165,
    category: "Breast-milk components",
    title: "Lactoferrin",
    message: "Lactoferrin binds iron and contributes to antimicrobial protection.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 166,
    category: "Breast-milk components",
    title: "Lysozyme",
    message: "Lysozyme contributes to antimicrobial activity in human milk.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 167,
    category: "Breast-milk components",
    title: "Lactose",
    message: "Lactose is a major milk carbohydrate and energy source.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 168,
    category: "Breast-milk components",
    title: "Lipids",
    message: "Milk lipids provide energy and important fatty acids.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 169,
    category: "Breast-milk components",
    title: "Proteins",
    message: "Milk proteins provide amino acids and several protective functions.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 170,
    category: "Breast-milk components",
    title: "Minerals",
    message: "Human milk contains minerals needed for infant growth, although needs change with age.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 171,
    category: "Breast-milk components",
    title: "Bioactive molecules",
    message: "Human milk contains hormones, growth factors and other bioactive molecules alongside nutrients.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 172,
    category: "Organ-focused learning",
    title: "Brain",
    message: "Breast milk provides nutrients and bioactive components within the nutritional environment supporting brain development.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO/NCBI",
  },
  {
    day: 173,
    category: "Organ-focused learning",
    title: "Eyes",
    message: "Long-chain fatty acids are part of the nutritional environment supporting visual and nervous-system development.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 174,
    category: "Organ-focused learning",
    title: "Gut",
    message: "Milk oligosaccharides and other components support the developing intestinal environment.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "NCBI",
  },
  {
    day: 175,
    category: "Organ-focused learning",
    title: "Lungs",
    message: "Breastfeeding is associated with protection against some respiratory infections.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 176,
    category: "Organ-focused learning",
    title: "Immune system",
    message: "Antibodies and other immune components help protect infants against infection.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO/NCBI",
  },
  {
    day: 177,
    category: "Organ-focused learning",
    title: "Bones",
    message: "Nutrients and minerals in milk contribute to normal infant growth and development.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO/NCBI",
  },
  {
    day: 178,
    category: "Organ-focused learning",
    title: "Blood",
    message: "Iron status should be monitored appropriately because human milk is not a high-iron food.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 179,
    category: "Organ-focused learning",
    title: "Heart",
    message: "Healthy infant nutrition supports normal growth of the cardiovascular system.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
  {
    day: 180,
    category: "Organ-focused learning",
    title: "Whole body",
    message: "Breastfeeding supports overall infant nutrition, growth and development.",
    whyItMatters: "This supports evidence-based breastfeeding education for infant nutrition, growth, development or protection.",
    motherTip: "If you have concerns about feeding, attachment, milk supply or your baby's growth, speak with a qualified health worker.",
    source: "WHO",
  },
];
